version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo ============================pre-build================================
      - aws s3 cp s3://rev-secret-bucket/hibernate.properties src/main/resources/hibernate.properties
      - aws s3 cp s3://rev-secret-bucket/application.properties src/main/resources/application.properties
      - aws s3 rm "s3://revagenda-jpa-ui/" --recursive #This removes old files from the bucket to clear them out
  build:
    commands:
      - echo ============================build================================
      - mvn package -q -DskipTests
      - cd UI/revagenda-ui
      - npm install
      - npm install -g @angular/cli
      - ng build
      - cd ../.. #move up two directories
  post_build:
    commands:
      - echo ============================post-build================================
      - pwd   # thses next few lines are fact-finding, looking for potential problems with the directory structure if the cd fails.
      - ls -al
      - ls -al /UI
      - ls -al /UI/revagenda-ui
      - cd UI/revagenda-ui/dist/revagenda-ui #moving back down into the location of our UI build artifacts
      - aws s3 cp "./" "s3://revagenda-jpa-ui/" --recursive #copying all files in this location to the static hosting S3 bucket
      - cd ../../../.. #mopving up 4 directories to get back into the source repo root
      - mv target/revagenda-*.*.war ROOT.war #copying up the server build artifacts (.WAR) from target into this directory for next commands
artifacts:
  files: #we are telling CodeBuild to hand off the following files to the deploy phase
    - ROOT.war
    - .ebextensions/**/*