version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11



  pre_build:
    commands:
      - echo ============================pre-build================================
      - aws s3 cp s3://rev-secret-bucket/hibernate.properties src/main/resources/hibernate.properties
      - aws s3 cp s3://rev-secret-bucket/application.properties src/main/resources/application.properties
      - aws s3 rm --recursive "s3://revagenda-jpa-ui/*"
  build:
    commands:
      - echo ============================build================================
      - mvn package -q -DskipTests
      - cd UI/revagenda-ui
      - npm install
      - npm install -g @angular/cli
      - ng build
      - cd ../..
  post_build:
    commands:
      - echo ============================post-build================================
      - cd UI/revagenda-ui/dist/revagenda-ui
      - aws s3 cp "./" "s3://revagenda-jpa-ui/" --recursive
      - cd ../../../..
      - pwd
      - mv target/revagenda-*.*.war ROOT.war
artifacts:
  files:
    - ROOT.war
    - .ebextensions/**/*